### ISSUE TITLE
How should I move a component / project to another folder?

### ISSUE THREAD

**Issue by rdthree** [camnewnham/HotLoader#4]
Firstly, I want to express my appreciation for this incredible project – thank you for creating it.

I have a question regarding the management of custom components. Currently, the component automatically utilizes the following directory: C:\Users\<user>\AppData\Local\Temp\HotLoader\HotComponent\Source\560b74a1-8355-4519-aee2-382f99bb2965

However, once I am satisfied with a component's development, I'm unsure how to relocate it while maintaining its seamless interaction with Grasshopper. Could you guide me on how to transfer the custom component code to a new folder, ensuring it continues to function as it did when initially set up by HotLoader? 

I'd like to keep working on projects, albeit in directories of my own choosing.

**Comment by camnewnham** [comment]
I'm glad you're enjoying it.

The general intention with HotComponents is that they remain saved in the GH definition only, and without dependencies other than HotLoader. As such it's important that the source code is also embedded rather than in a third party location, and it's also important that they can't change their own GUID (which is what allows them to be hot-loaded). 

However of course there is a natural progression from a prototype to a production plugin, so I'll think about how that could be managed in future.

For now, the best thing to do is probably to [create a new project via the wizard](https://developer.rhino3d.com/guides/rhinocommon/your-first-plugin-windows/) and follow the normal (albiet tedious) steps to build a "regular" plugin.
